# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1882a726-c36b-42ca-aa7e-6bc3d8b108fd";
      fsType = "ext4";
      options = ["noatime"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9310-02E7";
      fsType = "vfat";
      options = ["noatime" "fmask=0077" "dmask=0077" ];
    };
  fileSystems."/media/winData" =
    { device = "/dev/disk/by-uuid/A076696E766945DE";
      fsType = "ntfs";
      options = ["uid=1000" "gid=100" "umask=022" "windows_names" "exec" "permissions" "big_writes" "rw" ];
    };
  fileSystems."/home/stefan/extraData" =
    { device = "/dev/disk/by-uuid/ff511118-ba68-47d4-a5db-8557d09f631b";
      fsType = "ext4";
      options =  ["nofail"];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/11c9b03a-2f29-41df-bc20-52bbdf4ad9b0"; }
    ];

  #Download more RAM:
  zramSwap = {
    enable = true;
    priority = 100;
    algorithm = "lz4";
    memoryPercent = 50;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
